// automatically generated by the FlatBuffers compiler, do not modify

package motis.ppr;

public final class CrossingType {
  private CrossingType() { }
  public static final byte NONE = 0;
  public static final byte GENERATED = 1;
  public static final byte UNMARKED = 2;
  public static final byte MARKED = 3;
  public static final byte ISLAND = 4;
  public static final byte SIGNALS = 5;

  private static final String[] names = { "NONE", "GENERATED", "UNMARKED", "MARKED", "ISLAND", "SIGNALS", };

  public static String name(int e) { return names[e]; }
};

