// automatically generated by the FlatBuffers compiler, do not modify

package motis.ppr;

public final class EdgeType {
  private EdgeType() { }
  public static final byte CONNECTION = 0;
  public static final byte STREET = 1;
  public static final byte FOOTWAY = 2;
  public static final byte CROSSING = 3;
  public static final byte ELEVATOR = 4;

  private static final String[] names = { "CONNECTION", "STREET", "FOOTWAY", "CROSSING", "ELEVATOR", };

  public static String name(int e) { return names[e]; }
};

