// automatically generated by the FlatBuffers compiler, do not modify

package motis.ppr;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FootRoutingProfilesResponse extends Table {
  public static FootRoutingProfilesResponse getRootAsFootRoutingProfilesResponse(ByteBuffer _bb) { return getRootAsFootRoutingProfilesResponse(_bb, new FootRoutingProfilesResponse()); }
  public static FootRoutingProfilesResponse getRootAsFootRoutingProfilesResponse(ByteBuffer _bb, FootRoutingProfilesResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public FootRoutingProfilesResponse __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public FootRoutingProfileInfo profiles(int j) { return profiles(new FootRoutingProfileInfo(), j); }
  public FootRoutingProfileInfo profiles(FootRoutingProfileInfo obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int profilesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createFootRoutingProfilesResponse(FlatBufferBuilder builder,
      int profilesOffset) {
    builder.startObject(1);
    FootRoutingProfilesResponse.addProfiles(builder, profilesOffset);
    return FootRoutingProfilesResponse.endFootRoutingProfilesResponse(builder);
  }

  public static void startFootRoutingProfilesResponse(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addProfiles(FlatBufferBuilder builder, int profilesOffset) { builder.addOffset(0, profilesOffset, 0); }
  public static int createProfilesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startProfilesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFootRoutingProfilesResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

