// automatically generated by the FlatBuffers compiler, do not modify

package motis.ppr;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FootRoutingProfileInfo extends Table {
  public static FootRoutingProfileInfo getRootAsFootRoutingProfileInfo(ByteBuffer _bb) { return getRootAsFootRoutingProfileInfo(_bb, new FootRoutingProfileInfo()); }
  public static FootRoutingProfileInfo getRootAsFootRoutingProfileInfo(ByteBuffer _bb, FootRoutingProfileInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public FootRoutingProfileInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public double walkingSpeed() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createFootRoutingProfileInfo(FlatBufferBuilder builder,
      int nameOffset,
      double walking_speed) {
    builder.startObject(2);
    FootRoutingProfileInfo.addWalkingSpeed(builder, walking_speed);
    FootRoutingProfileInfo.addName(builder, nameOffset);
    return FootRoutingProfileInfo.endFootRoutingProfileInfo(builder);
  }

  public static void startFootRoutingProfileInfo(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addWalkingSpeed(FlatBufferBuilder builder, double walkingSpeed) { builder.addDouble(1, walkingSpeed, 0.0); }
  public static int endFootRoutingProfileInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // name
    return o;
  }
};

