// automatically generated by the FlatBuffers compiler, do not modify

package motis.ppr;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RouteStep extends Table {
  public static RouteStep getRootAsRouteStep(ByteBuffer _bb) { return getRootAsRouteStep(_bb, new RouteStep()); }
  public static RouteStep getRootAsRouteStep(ByteBuffer _bb, RouteStep obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RouteStep __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int stepType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public String streetName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer streetNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public int streetType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public int crossingType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public double distance() { int o = __offset(12); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double duration() { int o = __offset(14); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double accessibility() { int o = __offset(16); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public motis.Polyline path() { return path(new motis.Polyline()); }
  public motis.Polyline path(motis.Polyline obj) { int o = __offset(18); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public int elevationUp() { int o = __offset(20); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int elevationDown() { int o = __offset(22); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean inclineUp() { int o = __offset(24); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int handrail() { int o = __offset(26); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createRouteStep(FlatBufferBuilder builder,
      int step_type,
      int street_nameOffset,
      int street_type,
      int crossing_type,
      double distance,
      double duration,
      double accessibility,
      int pathOffset,
      int elevation_up,
      int elevation_down,
      boolean incline_up,
      int handrail) {
    builder.startObject(12);
    RouteStep.addAccessibility(builder, accessibility);
    RouteStep.addDuration(builder, duration);
    RouteStep.addDistance(builder, distance);
    RouteStep.addElevationDown(builder, elevation_down);
    RouteStep.addElevationUp(builder, elevation_up);
    RouteStep.addPath(builder, pathOffset);
    RouteStep.addStreetName(builder, street_nameOffset);
    RouteStep.addHandrail(builder, handrail);
    RouteStep.addInclineUp(builder, incline_up);
    RouteStep.addCrossingType(builder, crossing_type);
    RouteStep.addStreetType(builder, street_type);
    RouteStep.addStepType(builder, step_type);
    return RouteStep.endRouteStep(builder);
  }

  public static void startRouteStep(FlatBufferBuilder builder) { builder.startObject(12); }
  public static void addStepType(FlatBufferBuilder builder, int stepType) { builder.addByte(0, (byte)stepType, 0); }
  public static void addStreetName(FlatBufferBuilder builder, int streetNameOffset) { builder.addOffset(1, streetNameOffset, 0); }
  public static void addStreetType(FlatBufferBuilder builder, int streetType) { builder.addByte(2, (byte)streetType, 0); }
  public static void addCrossingType(FlatBufferBuilder builder, int crossingType) { builder.addByte(3, (byte)crossingType, 0); }
  public static void addDistance(FlatBufferBuilder builder, double distance) { builder.addDouble(4, distance, 0.0); }
  public static void addDuration(FlatBufferBuilder builder, double duration) { builder.addDouble(5, duration, 0.0); }
  public static void addAccessibility(FlatBufferBuilder builder, double accessibility) { builder.addDouble(6, accessibility, 0.0); }
  public static void addPath(FlatBufferBuilder builder, int pathOffset) { builder.addOffset(7, pathOffset, 0); }
  public static void addElevationUp(FlatBufferBuilder builder, int elevationUp) { builder.addInt(8, elevationUp, 0); }
  public static void addElevationDown(FlatBufferBuilder builder, int elevationDown) { builder.addInt(9, elevationDown, 0); }
  public static void addInclineUp(FlatBufferBuilder builder, boolean inclineUp) { builder.addBoolean(10, inclineUp, false); }
  public static void addHandrail(FlatBufferBuilder builder, int handrail) { builder.addByte(11, (byte)handrail, 0); }
  public static int endRouteStep(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

