// automatically generated by the FlatBuffers compiler, do not modify

package motis.ppr;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Route extends Table {
  public static Route getRootAsRoute(ByteBuffer _bb) { return getRootAsRoute(_bb, new Route()); }
  public static Route getRootAsRoute(ByteBuffer _bb, Route obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Route __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public double distance() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public int duration() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public double durationExact() { int o = __offset(8); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double durationDivision() { int o = __offset(10); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public int accessibility() { int o = __offset(12); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public double accessibilityExact() { int o = __offset(14); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double accessibilityDivision() { int o = __offset(16); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public motis.Position start() { return start(new motis.Position()); }
  public motis.Position start(motis.Position obj) { int o = __offset(18); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public motis.Position destination() { return destination(new motis.Position()); }
  public motis.Position destination(motis.Position obj) { int o = __offset(20); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public RouteStep steps(int j) { return steps(new RouteStep(), j); }
  public RouteStep steps(RouteStep obj, int j) { int o = __offset(22); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int stepsLength() { int o = __offset(22); return o != 0 ? __vector_len(o) : 0; }
  public Edge edges(int j) { return edges(new Edge(), j); }
  public Edge edges(Edge obj, int j) { int o = __offset(24); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int edgesLength() { int o = __offset(24); return o != 0 ? __vector_len(o) : 0; }
  public motis.Polyline path() { return path(new motis.Polyline()); }
  public motis.Polyline path(motis.Polyline obj) { int o = __offset(26); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public int elevationUp() { int o = __offset(28); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int elevationDown() { int o = __offset(30); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static void startRoute(FlatBufferBuilder builder) { builder.startObject(14); }
  public static void addDistance(FlatBufferBuilder builder, double distance) { builder.addDouble(0, distance, 0.0); }
  public static void addDuration(FlatBufferBuilder builder, int duration) { builder.addShort(1, (short)duration, 0); }
  public static void addDurationExact(FlatBufferBuilder builder, double durationExact) { builder.addDouble(2, durationExact, 0.0); }
  public static void addDurationDivision(FlatBufferBuilder builder, double durationDivision) { builder.addDouble(3, durationDivision, 0.0); }
  public static void addAccessibility(FlatBufferBuilder builder, int accessibility) { builder.addShort(4, (short)accessibility, 0); }
  public static void addAccessibilityExact(FlatBufferBuilder builder, double accessibilityExact) { builder.addDouble(5, accessibilityExact, 0.0); }
  public static void addAccessibilityDivision(FlatBufferBuilder builder, double accessibilityDivision) { builder.addDouble(6, accessibilityDivision, 0.0); }
  public static void addStart(FlatBufferBuilder builder, int startOffset) { builder.addStruct(7, startOffset, 0); }
  public static void addDestination(FlatBufferBuilder builder, int destinationOffset) { builder.addStruct(8, destinationOffset, 0); }
  public static void addSteps(FlatBufferBuilder builder, int stepsOffset) { builder.addOffset(9, stepsOffset, 0); }
  public static int createStepsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startStepsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addEdges(FlatBufferBuilder builder, int edgesOffset) { builder.addOffset(10, edgesOffset, 0); }
  public static int createEdgesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEdgesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addPath(FlatBufferBuilder builder, int pathOffset) { builder.addOffset(11, pathOffset, 0); }
  public static void addElevationUp(FlatBufferBuilder builder, int elevationUp) { builder.addInt(12, elevationUp, 0); }
  public static void addElevationDown(FlatBufferBuilder builder, int elevationDown) { builder.addInt(13, elevationDown, 0); }
  public static int endRoute(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

