// automatically generated by the FlatBuffers compiler, do not modify

package motis.ppr;

public final class SearchDirection {
  private SearchDirection() { }
  public static final byte Forward = 0;
  public static final byte Backward = 1;

  private static final String[] names = { "Forward", "Backward", };

  public static String name(int e) { return names[e]; }
};

