// automatically generated by the FlatBuffers compiler, do not modify

package motis.ppr;

public final class StreetType {
  private StreetType() { }
  public static final byte NONE = 0;
  public static final byte TRACK = 1;
  public static final byte FOOTWAY = 2;
  public static final byte PATH = 3;
  public static final byte CYCLEWAY = 4;
  public static final byte BRIDLEWAY = 5;
  public static final byte STAIRS = 6;
  public static final byte ESCALATOR = 7;
  public static final byte MOVING_WALKWAY = 8;
  public static final byte SERVICE = 9;
  public static final byte PEDESTRIAN = 10;
  public static final byte LIVING = 11;
  public static final byte RESIDENTIAL = 12;
  public static final byte UNCLASSIFIED = 13;
  public static final byte TERTIARY = 14;
  public static final byte SECONDARY = 15;
  public static final byte PRIMARY = 16;
  public static final byte RAIL = 17;
  public static final byte TRAM = 18;

  private static final String[] names = { "NONE", "TRACK", "FOOTWAY", "PATH", "CYCLEWAY", "BRIDLEWAY", "STAIRS", "ESCALATOR", "MOVING_WALKWAY", "SERVICE", "PEDESTRIAN", "LIVING", "RESIDENTIAL", "UNCLASSIFIED", "TERTIARY", "SECONDARY", "PRIMARY", "RAIL", "TRAM", };

  public static String name(int e) { return names[e]; }
};

