// automatically generated by the FlatBuffers compiler, do not modify

package motis.ppr;

public final class TriState {
  private TriState() { }
  public static final byte UNKNOWN = 0;
  public static final byte NO = 1;
  public static final byte YES = 2;

  private static final String[] names = { "UNKNOWN", "NO", "YES", };

  public static String name(int e) { return names[e]; }
};

