services:
  motis:
    platform: linux/amd64
    image: motis:latest
    container_name: motis
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    user: motis
    restart: unless-stopped
    command: ["/motis", "server", "/data"]
  motis-ui:
    build:
      context: ./ui
    image: motis-ui:latest
    container_name: motis-ui
    ports:
      - "8081:80"
    environment:
      - MOTIS_BACKEND_URL=${MOTIS_BACKEND_URL:-http://localhost:8080}
    depends_on:
      - motis
    restart: unless-stopped
