// automatically generated by the FlatBuffers compiler, do not modify

package motis.intermodal;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CarParking extends Table {
  public static CarParking getRootAsCarParking(ByteBuffer _bb) { return getRootAsCarParking(_bb, new CarParking()); }
  public static CarParking getRootAsCarParking(ByteBuffer _bb, CarParking obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CarParking __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int maxCarDuration() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public motis.ppr.SearchOptions pprSearchOptions() { return pprSearchOptions(new motis.ppr.SearchOptions()); }
  public motis.ppr.SearchOptions pprSearchOptions(motis.ppr.SearchOptions obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createCarParking(FlatBufferBuilder builder,
      int max_car_duration,
      int ppr_search_optionsOffset) {
    builder.startObject(2);
    CarParking.addPprSearchOptions(builder, ppr_search_optionsOffset);
    CarParking.addMaxCarDuration(builder, max_car_duration);
    return CarParking.endCarParking(builder);
  }

  public static void startCarParking(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addMaxCarDuration(FlatBufferBuilder builder, int maxCarDuration) { builder.addInt(0, maxCarDuration, 0); }
  public static void addPprSearchOptions(FlatBufferBuilder builder, int pprSearchOptionsOffset) { builder.addOffset(1, pprSearchOptionsOffset, 0); }
  public static int endCarParking(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

