// automatically generated by the FlatBuffers compiler, do not modify

package motis.intermodal;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Foot extends Table {
  public static Foot getRootAsFoot(ByteBuffer _bb) { return getRootAsFoot(_bb, new Foot()); }
  public static Foot getRootAsFoot(ByteBuffer _bb, Foot obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Foot __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int maxDuration() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createFoot(FlatBufferBuilder builder,
      int max_duration) {
    builder.startObject(1);
    Foot.addMaxDuration(builder, max_duration);
    return Foot.endFoot(builder);
  }

  public static void startFoot(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addMaxDuration(FlatBufferBuilder builder, int maxDuration) { builder.addInt(0, maxDuration, 0); }
  public static int endFoot(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

