// automatically generated by the FlatBuffers compiler, do not modify

package motis.intermodal;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class InputPosition extends Table {
  public static InputPosition getRootAsInputPosition(ByteBuffer _bb) { return getRootAsInputPosition(_bb, new InputPosition()); }
  public static InputPosition getRootAsInputPosition(ByteBuffer _bb, InputPosition obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public InputPosition __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public double lat() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double lng() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createInputPosition(FlatBufferBuilder builder,
      double lat,
      double lng) {
    builder.startObject(2);
    InputPosition.addLng(builder, lng);
    InputPosition.addLat(builder, lat);
    return InputPosition.endInputPosition(builder);
  }

  public static void startInputPosition(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addLat(FlatBufferBuilder builder, double lat) { builder.addDouble(0, lat, 0.0); }
  public static void addLng(FlatBufferBuilder builder, double lng) { builder.addDouble(1, lng, 0.0); }
  public static int endInputPosition(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

