// automatically generated by the FlatBuffers compiler, do not modify

package motis.intermodal;

public final class IntermodalDestination {
  private IntermodalDestination() { }
  public static final byte NONE = 0;
  public static final byte InputStation = 1;
  public static final byte InputPosition = 2;

  private static final String[] names = { "NONE", "InputStation", "InputPosition", };

  public static String name(int e) { return names[e]; }
};

