// automatically generated by the FlatBuffers compiler, do not modify

package motis.intermodal;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class IntermodalOntripStart extends Table {
  public static IntermodalOntripStart getRootAsIntermodalOntripStart(ByteBuffer _bb) { return getRootAsIntermodalOntripStart(_bb, new IntermodalOntripStart()); }
  public static IntermodalOntripStart getRootAsIntermodalOntripStart(ByteBuffer _bb, IntermodalOntripStart obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public IntermodalOntripStart __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public motis.Position position() { return position(new motis.Position()); }
  public motis.Position position(motis.Position obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long departureTime() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }

  public static void startIntermodalOntripStart(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addPosition(FlatBufferBuilder builder, int positionOffset) { builder.addStruct(0, positionOffset, 0); }
  public static void addDepartureTime(FlatBufferBuilder builder, long departureTime) { builder.addLong(1, departureTime, 0); }
  public static int endIntermodalOntripStart(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

