// automatically generated by the FlatBuffers compiler, do not modify

package motis.intermodal;

public final class IntermodalStart {
  private IntermodalStart() { }
  public static final byte NONE = 0;
  public static final byte IntermodalOntripStart = 1;
  public static final byte IntermodalPretripStart = 2;
  public static final byte OntripTrainStart = 3;
  public static final byte OntripStationStart = 4;
  public static final byte PretripStart = 5;

  private static final String[] names = { "NONE", "IntermodalOntripStart", "IntermodalPretripStart", "OntripTrainStart", "OntripStationStart", "PretripStart", };

  public static String name(int e) { return names[e]; }
};

