// automatically generated by the FlatBuffers compiler, do not modify

package motis.intermodal;

public final class Mode {
  private Mode() { }
  public static final byte NONE = 0;
  public static final byte Foot = 1;
  public static final byte Bike = 2;
  public static final byte Car = 3;
  public static final byte FootPPR = 4;
  public static final byte CarParking = 5;
  public static final byte GBFS = 6;

  private static final String[] names = { "NONE", "Foot", "Bike", "Car", "FootPPR", "CarParking", "GBFS", };

  public static String name(int e) { return names[e]; }
};

