InputStation:
  description: |
    An input station is a station from user input. If the user used the
    auto-completion function and the station ID is available, then the `id`
    field is used to resolve the station. If this is not the case (the user just
    entered a string), the `name` field is filled with a (possibly incomplete or
    misspelled) station name. In the latter case, MOTIS will use the first guess
    from the station auto-complete to resolve the station `id`.
  fields:
    id:
      description: The station ID if available. May be empty if `name` is set.
    name:
      description: The station name if no ID is available. May be empty if `id` is set.
MumoEdge:
  description: TODO
  fields:
    from_station_id:
      description: TODO
    to_station_id:
      description: TODO
    duration:
      description: TODO
    price:
      description: TODO
    accessibility:
      description: TODO
    mumo_id:
      description: TODO
PeriodicMumoEdge:
  description: TODO
  fields:
    edge:
      description: TODO
    interval:
      description: TODO
TimeDependentMumoEdge:
  description: TODO
  fields:
    edge:
      description: TODO
    interval:
      description: TODO
HotelEdge:
  description: TODO
  fields:
    edge:
      description: TODO
    earliest_checkout_time:
      description: TODO
    min_stay_duration:
      description: TODO
AdditionalEdge:
  description: TODO
AdditionalEdgeWrapper:
  description: TODO
  fields:
    additional_edge:
      description: TODO
OntripTrainStart:
  description: TODO
  fields:
    trip:
      description: TODO
    station:
      description: TODO
    arrival_time:
      description: TODO
OntripStationStart:
  description: TODO
  fields:
    station:
      description: TODO
    departure_time:
      description: TODO
PretripStart:
  description: TODO
  fields:
    station:
      description: TODO
    interval:
      description: TODO
    min_connection_count:
      description: TODO
    extend_interval_earlier:
      description: TODO
    extend_interval_later:
      description: TODO
Start:
  description: TODO
Via:
  description: TODO
  fields:
    station:
      description: TODO
    stay_duration:
      description: TODO
SearchType:
  description: TODO
RoutingRequest:
  description: TODO
  fields:
    start:
      description: TODO
    destination:
      description: TODO
    search_type:
      description: TODO
    search_dir:
      description: TODO
    via:
      description: TODO
    additional_edges:
      description: TODO
    use_start_metas:
      description: TODO
    use_dest_metas:
      description: TODO
    use_start_footpaths:
      description: TODO
    schedule:
      description: |
        The schedule ID.

        This should always be set to `0` unless a paxmon parallel universe
        should be used for routing, in which case it should be set to the
        schedule ID (not universe ID) of that universe.
      examples:
        - 0
    timeout:
      description: TODO
    allowed_claszes:
      description: TODO
    max_transfers:
      description: |
        The maximum number of transfers allowed per journey.

        If set to `-1` (the default value if not specified), the internal
        default value is used.
    bike_transport:
      description: |
        Whether only journeys where bike transport is allowed should be considered.

        If set to `true`, only trips where bike transport is allowed can be
        used.
    min_transfer_time:
      description: |
        The minimum transfer time in minutes.

        Set to `0` (the default value if not specified) to use the default
        transfer times from the timetable.
    transfer_time_factor:
      description: |
        Multiply all transfer times by this factor. Must be >= 1.0.
        The minimum transfer time is not multiplied by this factor.

        Set to `1.0` (the default value if not specified) to use the default
        transfer times from the timetable.
RoutingResponse:
  description: TODO
  fields:
    statistics:
      description: TODO
    connections:
      description: TODO
    interval_begin:
      description: TODO
    interval_end:
      description: TODO
    direct_connections:
      description: TODO
