// automatically generated by the FlatBuffers compiler, do not modify

package motis.routing;

public final class AdditionalEdge {
  private AdditionalEdge() { }
  public static final byte NONE = 0;
  public static final byte MumoEdge = 1;
  public static final byte PeriodicMumoEdge = 2;
  public static final byte TimeDependentMumoEdge = 3;
  public static final byte HotelEdge = 4;

  private static final String[] names = { "NONE", "MumoEdge", "PeriodicMumoEdge", "TimeDependentMumoEdge", "HotelEdge", };

  public static String name(int e) { return names[e]; }
};

