// automatically generated by the FlatBuffers compiler, do not modify

package motis.routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class HotelEdge extends Table {
  public static HotelEdge getRootAsHotelEdge(ByteBuffer _bb) { return getRootAsHotelEdge(_bb, new HotelEdge()); }
  public static HotelEdge getRootAsHotelEdge(ByteBuffer _bb, HotelEdge obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public HotelEdge __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public MumoEdge edge() { return edge(new MumoEdge()); }
  public MumoEdge edge(MumoEdge obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public int earliestCheckoutTime() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public int minStayDuration() { int o = __offset(8); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }

  public static int createHotelEdge(FlatBufferBuilder builder,
      int edgeOffset,
      int earliest_checkout_time,
      int min_stay_duration) {
    builder.startObject(3);
    HotelEdge.addEdge(builder, edgeOffset);
    HotelEdge.addMinStayDuration(builder, min_stay_duration);
    HotelEdge.addEarliestCheckoutTime(builder, earliest_checkout_time);
    return HotelEdge.endHotelEdge(builder);
  }

  public static void startHotelEdge(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addEdge(FlatBufferBuilder builder, int edgeOffset) { builder.addOffset(0, edgeOffset, 0); }
  public static void addEarliestCheckoutTime(FlatBufferBuilder builder, int earliestCheckoutTime) { builder.addShort(1, (short)earliestCheckoutTime, 0); }
  public static void addMinStayDuration(FlatBufferBuilder builder, int minStayDuration) { builder.addShort(2, (short)minStayDuration, 0); }
  public static int endHotelEdge(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

