// automatically generated by the FlatBuffers compiler, do not modify

package motis.routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class InputStation extends Table {
  public static InputStation getRootAsInputStation(ByteBuffer _bb) { return getRootAsInputStation(_bb, new InputStation()); }
  public static InputStation getRootAsInputStation(ByteBuffer _bb, InputStation obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public InputStation __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createInputStation(FlatBufferBuilder builder,
      int idOffset,
      int nameOffset) {
    builder.startObject(2);
    InputStation.addName(builder, nameOffset);
    InputStation.addId(builder, idOffset);
    return InputStation.endInputStation(builder);
  }

  public static void startInputStation(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static int endInputStation(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

