// automatically generated by the FlatBuffers compiler, do not modify

package motis.routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class OntripTrainStart extends Table {
  public static OntripTrainStart getRootAsOntripTrainStart(ByteBuffer _bb) { return getRootAsOntripTrainStart(_bb, new OntripTrainStart()); }
  public static OntripTrainStart getRootAsOntripTrainStart(ByteBuffer _bb, OntripTrainStart obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public OntripTrainStart __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public motis.TripId trip() { return trip(new motis.TripId()); }
  public motis.TripId trip(motis.TripId obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public InputStation station() { return station(new InputStation()); }
  public InputStation station(InputStation obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public long arrivalTime() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }

  public static int createOntripTrainStart(FlatBufferBuilder builder,
      int tripOffset,
      int stationOffset,
      long arrival_time) {
    builder.startObject(3);
    OntripTrainStart.addArrivalTime(builder, arrival_time);
    OntripTrainStart.addStation(builder, stationOffset);
    OntripTrainStart.addTrip(builder, tripOffset);
    return OntripTrainStart.endOntripTrainStart(builder);
  }

  public static void startOntripTrainStart(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addTrip(FlatBufferBuilder builder, int tripOffset) { builder.addOffset(0, tripOffset, 0); }
  public static void addStation(FlatBufferBuilder builder, int stationOffset) { builder.addOffset(1, stationOffset, 0); }
  public static void addArrivalTime(FlatBufferBuilder builder, long arrivalTime) { builder.addLong(2, arrivalTime, 0); }
  public static int endOntripTrainStart(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

