// automatically generated by the FlatBuffers compiler, do not modify

package motis.routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RoutingResponse extends Table {
  public static RoutingResponse getRootAsRoutingResponse(ByteBuffer _bb) { return getRootAsRoutingResponse(_bb, new RoutingResponse()); }
  public static RoutingResponse getRootAsRoutingResponse(ByteBuffer _bb, RoutingResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RoutingResponse __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public motis.Statistics statistics(int j) { return statistics(new motis.Statistics(), j); }
  public motis.Statistics statistics(motis.Statistics obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int statisticsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public motis.Connection connections(int j) { return connections(new motis.Connection(), j); }
  public motis.Connection connections(motis.Connection obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int connectionsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public long intervalBegin() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long intervalEnd() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public motis.DirectConnection directConnections(int j) { return directConnections(new motis.DirectConnection(), j); }
  public motis.DirectConnection directConnections(motis.DirectConnection obj, int j) { int o = __offset(12); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int directConnectionsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }

  public static int createRoutingResponse(FlatBufferBuilder builder,
      int statisticsOffset,
      int connectionsOffset,
      long interval_begin,
      long interval_end,
      int direct_connectionsOffset) {
    builder.startObject(5);
    RoutingResponse.addIntervalEnd(builder, interval_end);
    RoutingResponse.addIntervalBegin(builder, interval_begin);
    RoutingResponse.addDirectConnections(builder, direct_connectionsOffset);
    RoutingResponse.addConnections(builder, connectionsOffset);
    RoutingResponse.addStatistics(builder, statisticsOffset);
    return RoutingResponse.endRoutingResponse(builder);
  }

  public static void startRoutingResponse(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addStatistics(FlatBufferBuilder builder, int statisticsOffset) { builder.addOffset(0, statisticsOffset, 0); }
  public static int createStatisticsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startStatisticsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addConnections(FlatBufferBuilder builder, int connectionsOffset) { builder.addOffset(1, connectionsOffset, 0); }
  public static int createConnectionsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startConnectionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addIntervalBegin(FlatBufferBuilder builder, long intervalBegin) { builder.addLong(2, intervalBegin, 0); }
  public static void addIntervalEnd(FlatBufferBuilder builder, long intervalEnd) { builder.addLong(3, intervalEnd, 0); }
  public static void addDirectConnections(FlatBufferBuilder builder, int directConnectionsOffset) { builder.addOffset(4, directConnectionsOffset, 0); }
  public static int createDirectConnectionsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startDirectConnectionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRoutingResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

