// automatically generated by the FlatBuffers compiler, do not modify

package motis.routing;

public final class SearchType {
  private SearchType() { }
  public static final byte Default = 0;
  public static final byte SingleCriterion = 1;
  public static final byte SingleCriterionNoIntercity = 2;
  public static final byte LateConnections = 3;
  public static final byte LateConnectionsTest = 4;
  public static final byte Accessibility = 5;
  public static final byte DefaultPrice = 6;
  public static final byte DefaultPriceRegional = 7;

  private static final String[] names = { "Default", "SingleCriterion", "SingleCriterionNoIntercity", "LateConnections", "LateConnectionsTest", "Accessibility", "DefaultPrice", "DefaultPriceRegional", };

  public static String name(int e) { return names[e]; }
};

