// automatically generated by the FlatBuffers compiler, do not modify

package motis.routing;

public final class Start {
  private Start() { }
  public static final byte NONE = 0;
  public static final byte OntripTrainStart = 1;
  public static final byte OntripStationStart = 2;
  public static final byte PretripStart = 3;

  private static final String[] names = { "NONE", "OntripTrainStart", "OntripStationStart", "PretripStart", };

  public static String name(int e) { return names[e]; }
};

