// automatically generated by the FlatBuffers compiler, do not modify

package motis.routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Via extends Table {
  public static Via getRootAsVia(ByteBuffer _bb) { return getRootAsVia(_bb, new Via()); }
  public static Via getRootAsVia(ByteBuffer _bb, Via obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Via __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public InputStation station() { return station(new InputStation()); }
  public InputStation station(InputStation obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public long stayDuration() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }

  public static int createVia(FlatBufferBuilder builder,
      int stationOffset,
      long stay_duration) {
    builder.startObject(2);
    Via.addStayDuration(builder, stay_duration);
    Via.addStation(builder, stationOffset);
    return Via.endVia(builder);
  }

  public static void startVia(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addStation(FlatBufferBuilder builder, int stationOffset) { builder.addOffset(0, stationOffset, 0); }
  public static void addStayDuration(FlatBufferBuilder builder, long stayDuration) { builder.addInt(1, (int)stayDuration, 0); }
  public static int endVia(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

