// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { ReverseGeocodeData, ReverseGeocodeError, ReverseGeocodeResponse, GeocodeData, GeocodeError, GeocodeResponse, TripData, TripError, TripResponse, StoptimesData, StoptimesError, StoptimesResponse, PlanData, PlanError, PlanResponse, LevelsData, LevelsError, LevelsResponse, FootpathsData, FootpathsError, FootpathsResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Translate coordinates to the closest address(es)/places/stops.
 */
export const reverseGeocode = <ThrowOnError extends boolean = false>(options: Options<ReverseGeocodeData, ThrowOnError>) => { return (options?.client ?? client).get<ReverseGeocodeResponse, ReverseGeocodeError, ThrowOnError>({
    ...options,
    url: '/api/v1/reverse-geocode'
}); };

/**
 * Autocompletion & geocoding that resolves user input addresses including coordinates
 */
export const geocode = <ThrowOnError extends boolean = false>(options: Options<GeocodeData, ThrowOnError>) => { return (options?.client ?? client).get<GeocodeResponse, GeocodeError, ThrowOnError>({
    ...options,
    url: '/api/v1/geocode'
}); };

/**
 * Get a trip as itinerary
 */
export const trip = <ThrowOnError extends boolean = false>(options: Options<TripData, ThrowOnError>) => { return (options?.client ?? client).get<TripResponse, TripError, ThrowOnError>({
    ...options,
    url: '/api/v1/trip'
}); };

/**
 * Get the next N departures or arrivals of a stop sorted by time
 */
export const stoptimes = <ThrowOnError extends boolean = false>(options: Options<StoptimesData, ThrowOnError>) => { return (options?.client ?? client).get<StoptimesResponse, StoptimesError, ThrowOnError>({
    ...options,
    url: '/api/v1/stoptimes'
}); };

/**
 * Computes optimal connections from one place to another.
 */
export const plan = <ThrowOnError extends boolean = false>(options: Options<PlanData, ThrowOnError>) => { return (options?.client ?? client).get<PlanResponse, PlanError, ThrowOnError>({
    ...options,
    url: '/api/v1/plan'
}); };

/**
 * Get all available levels for a map section
 */
export const levels = <ThrowOnError extends boolean = false>(options: Options<LevelsData, ThrowOnError>) => { return (options?.client ?? client).get<LevelsResponse, LevelsError, ThrowOnError>({
    ...options,
    url: '/api/v1/levels'
}); };

/**
 * Prints all footpaths of a timetable location (track, bus stop, etc.)
 */
export const footpaths = <ThrowOnError extends boolean = false>(options: Options<FootpathsData, ThrowOnError>) => { return (options?.client ?? client).get<FootpathsResponse, FootpathsError, ThrowOnError>({
    ...options,
    url: '/api/debug/footpaths'
}); };