// automatically generated by the FlatBuffers compiler, do not modify

package motis;

public final class ConnectionStatus {
  private ConnectionStatus() { }
  public static final byte OK = 0;
  public static final byte INTERCHANGE_INVALID = 1;
  public static final byte TRAIN_HAS_BEEN_CANCELED = 2;
  public static final byte INVALID = 3;

  private static final String[] names = { "OK", "INTERCHANGE_INVALID", "TRAIN_HAS_BEEN_CANCELED", "INVALID", };

  public static String name(int e) { return names[e]; }
};

