// automatically generated by the FlatBuffers compiler, do not modify

package motis;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Connection extends Table {
  public static Connection getRootAsConnection(ByteBuffer _bb) { return getRootAsConnection(_bb, new Connection()); }
  public static Connection getRootAsConnection(ByteBuffer _bb, Connection obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Connection __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public Stop stops(int j) { return stops(new Stop(), j); }
  public Stop stops(Stop obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int stopsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public MoveWrapper transports(int j) { return transports(new MoveWrapper(), j); }
  public MoveWrapper transports(MoveWrapper obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int transportsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public Trip trips(int j) { return trips(new Trip(), j); }
  public Trip trips(Trip obj, int j) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int tripsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public Attribute attributes(int j) { return attributes(new Attribute(), j); }
  public Attribute attributes(Attribute obj, int j) { int o = __offset(10); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int attributesLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public FreeText freeTexts(int j) { return freeTexts(new FreeText(), j); }
  public FreeText freeTexts(FreeText obj, int j) { int o = __offset(12); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int freeTextsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public Problem problems(int j) { return problems(new Problem(), j); }
  public Problem problems(Problem obj, int j) { int o = __offset(14); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int problemsLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public int nightPenalty() { int o = __offset(16); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public int dbCosts() { int o = __offset(18); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public byte status() { int o = __offset(20); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createConnection(FlatBufferBuilder builder,
      int stopsOffset,
      int transportsOffset,
      int tripsOffset,
      int attributesOffset,
      int free_textsOffset,
      int problemsOffset,
      int night_penalty,
      int db_costs,
      byte status) {
    builder.startObject(9);
    Connection.addProblems(builder, problemsOffset);
    Connection.addFreeTexts(builder, free_textsOffset);
    Connection.addAttributes(builder, attributesOffset);
    Connection.addTrips(builder, tripsOffset);
    Connection.addTransports(builder, transportsOffset);
    Connection.addStops(builder, stopsOffset);
    Connection.addDbCosts(builder, db_costs);
    Connection.addNightPenalty(builder, night_penalty);
    Connection.addStatus(builder, status);
    return Connection.endConnection(builder);
  }

  public static void startConnection(FlatBufferBuilder builder) { builder.startObject(9); }
  public static void addStops(FlatBufferBuilder builder, int stopsOffset) { builder.addOffset(0, stopsOffset, 0); }
  public static int createStopsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startStopsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addTransports(FlatBufferBuilder builder, int transportsOffset) { builder.addOffset(1, transportsOffset, 0); }
  public static int createTransportsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTransportsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addTrips(FlatBufferBuilder builder, int tripsOffset) { builder.addOffset(2, tripsOffset, 0); }
  public static int createTripsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTripsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addAttributes(FlatBufferBuilder builder, int attributesOffset) { builder.addOffset(3, attributesOffset, 0); }
  public static int createAttributesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAttributesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addFreeTexts(FlatBufferBuilder builder, int freeTextsOffset) { builder.addOffset(4, freeTextsOffset, 0); }
  public static int createFreeTextsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startFreeTextsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addProblems(FlatBufferBuilder builder, int problemsOffset) { builder.addOffset(5, problemsOffset, 0); }
  public static int createProblemsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startProblemsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addNightPenalty(FlatBufferBuilder builder, int nightPenalty) { builder.addShort(6, (short)nightPenalty, 0); }
  public static void addDbCosts(FlatBufferBuilder builder, int dbCosts) { builder.addShort(7, (short)dbCosts, 0); }
  public static void addStatus(FlatBufferBuilder builder, byte status) { builder.addByte(8, status, 0); }
  public static int endConnection(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

