// automatically generated by the FlatBuffers compiler, do not modify

package motis;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Destination extends Table {
  public static Destination getRootAsDestination(ByteBuffer _bb) { return getRootAsDestination(_bb, new Destination()); }
  public static Destination getRootAsDestination(ByteBuffer _bb, Destination obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Destination __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String target() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer targetAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createDestination(FlatBufferBuilder builder,
      byte type,
      int targetOffset) {
    builder.startObject(2);
    Destination.addTarget(builder, targetOffset);
    Destination.addType(builder, type);
    return Destination.endDestination(builder);
  }

  public static void startDestination(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addTarget(FlatBufferBuilder builder, int targetOffset) { builder.addOffset(1, targetOffset, 0); }
  public static int endDestination(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

