// automatically generated by the FlatBuffers compiler, do not modify

package motis;

public final class DestinationType {
  private DestinationType() { }
  public static final byte Module = 0;
  public static final byte Topic = 1;

  private static final String[] names = { "Module", "Topic", };

  public static String name(int e) { return names[e]; }
};

