// automatically generated by the FlatBuffers compiler, do not modify

package motis;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class DirectConnection extends Table {
  public static DirectConnection getRootAsDirectConnection(ByteBuffer _bb) { return getRootAsDirectConnection(_bb, new DirectConnection()); }
  public static DirectConnection getRootAsDirectConnection(ByteBuffer _bb, DirectConnection obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public DirectConnection __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long duration() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public long accessibility() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public String mumoType() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mumoTypeAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }

  public static int createDirectConnection(FlatBufferBuilder builder,
      long duration,
      long accessibility,
      int mumo_typeOffset) {
    builder.startObject(3);
    DirectConnection.addMumoType(builder, mumo_typeOffset);
    DirectConnection.addAccessibility(builder, accessibility);
    DirectConnection.addDuration(builder, duration);
    return DirectConnection.endDirectConnection(builder);
  }

  public static void startDirectConnection(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addDuration(FlatBufferBuilder builder, long duration) { builder.addInt(0, (int)duration, 0); }
  public static void addAccessibility(FlatBufferBuilder builder, long accessibility) { builder.addInt(1, (int)accessibility, 0); }
  public static void addMumoType(FlatBufferBuilder builder, int mumoTypeOffset) { builder.addOffset(2, mumoTypeOffset, 0); }
  public static int endDirectConnection(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

