// automatically generated by the FlatBuffers compiler, do not modify

package motis;

public final class EventType {
  private EventType() { }
  public static final byte DEP = 0;
  public static final byte ARR = 1;

  private static final String[] names = { "DEP", "ARR", };

  public static String name(int e) { return names[e]; }
};

