// automatically generated by the FlatBuffers compiler, do not modify

package motis;

public final class HTTPMethod {
  private HTTPMethod() { }
  public static final byte GET = 0;
  public static final byte POST = 1;
  public static final byte PUT = 2;
  public static final byte DELETE = 3;
  public static final byte OPTIONS = 4;

  private static final String[] names = { "GET", "POST", "PUT", "DELETE", "OPTIONS", };

  public static String name(int e) { return names[e]; }
};

