// automatically generated by the FlatBuffers compiler, do not modify

package motis;

public final class HTTPStatus {
  private HTTPStatus() { }
  public static final byte OK = 0;
  public static final byte INTERNAL_SERVER_ERROR = 1;

  private static final String[] names = { "OK", "INTERNAL_SERVER_ERROR", };

  public static String name(int e) { return names[e]; }
};

