// automatically generated by the FlatBuffers compiler, do not modify

package motis;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MotisNoMessage extends Table {
  public static MotisNoMessage getRootAsMotisNoMessage(ByteBuffer _bb) { return getRootAsMotisNoMessage(_bb, new MotisNoMessage()); }
  public static MotisNoMessage getRootAsMotisNoMessage(ByteBuffer _bb, MotisNoMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public MotisNoMessage __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }


  public static void startMotisNoMessage(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endMotisNoMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

