// automatically generated by the FlatBuffers compiler, do not modify

package motis;

public final class Move {
  private Move() { }
  public static final byte NONE = 0;
  public static final byte Transport = 1;
  public static final byte Walk = 2;

  private static final String[] names = { "NONE", "Transport", "Walk", };

  public static String name(int e) { return names[e]; }
};

