// automatically generated by the FlatBuffers compiler, do not modify

package motis;

public final class ProblemType {
  private ProblemType() { }
  public static final byte NO_PROBLEM = 0;
  public static final byte INTERCHANGE_TIME_VIOLATED = 1;
  public static final byte CANCELED_TRAIN = 2;

  private static final String[] names = { "NO_PROBLEM", "INTERCHANGE_TIME_VIOLATED", "CANCELED_TRAIN", };

  public static String name(int e) { return names[e]; }
};

