// automatically generated by the FlatBuffers compiler, do not modify

package motis;

public final class TimestampReason {
  private TimestampReason() { }
  public static final byte SCHEDULE = 0;
  public static final byte REPAIR = 1;
  public static final byte IS = 2;
  public static final byte PROPAGATION = 3;
  public static final byte FORECAST = 4;

  private static final String[] names = { "SCHEDULE", "REPAIR", "IS", "PROPAGATION", "FORECAST", };

  public static String name(int e) { return names[e]; }
};

