// automatically generated by the FlatBuffers compiler, do not modify

package motis;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Transport extends Table {
  public static Transport getRootAsTransport(ByteBuffer _bb) { return getRootAsTransport(_bb, new Transport()); }
  public static Transport getRootAsTransport(ByteBuffer _bb, Transport obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Transport __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public Range range() { return range(new Range()); }
  public Range range(Range obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long clasz() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public String lineId() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer lineIdAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public String name() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public String provider() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer providerAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public String direction() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer directionAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }

  public static void startTransport(FlatBufferBuilder builder) { builder.startObject(6); }
  public static void addRange(FlatBufferBuilder builder, int rangeOffset) { builder.addStruct(0, rangeOffset, 0); }
  public static void addClasz(FlatBufferBuilder builder, long clasz) { builder.addInt(1, (int)clasz, 0); }
  public static void addLineId(FlatBufferBuilder builder, int lineIdOffset) { builder.addOffset(2, lineIdOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(3, nameOffset, 0); }
  public static void addProvider(FlatBufferBuilder builder, int providerOffset) { builder.addOffset(4, providerOffset, 0); }
  public static void addDirection(FlatBufferBuilder builder, int directionOffset) { builder.addOffset(5, directionOffset, 0); }
  public static int endTransport(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

