// automatically generated by the FlatBuffers compiler, do not modify

package motis;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TripInfo extends Table {
  public static TripInfo getRootAsTripInfo(ByteBuffer _bb) { return getRootAsTripInfo(_bb, new TripInfo()); }
  public static TripInfo getRootAsTripInfo(ByteBuffer _bb, TripInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public TripInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public motis.TripId id() { return id(new motis.TripId()); }
  public motis.TripId id(motis.TripId obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public motis.Transport transport() { return transport(new motis.Transport()); }
  public motis.Transport transport(motis.Transport obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createTripInfo(FlatBufferBuilder builder,
      int idOffset,
      int transportOffset) {
    builder.startObject(2);
    TripInfo.addTransport(builder, transportOffset);
    TripInfo.addId(builder, idOffset);
    return TripInfo.endTripInfo(builder);
  }

  public static void startTripInfo(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addTransport(FlatBufferBuilder builder, int transportOffset) { builder.addOffset(1, transportOffset, 0); }
  public static int endTripInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

