// automatically generated by the FlatBuffers compiler, do not modify

package motis.lookup;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LookupStationEventsRequest extends Table {
  public static LookupStationEventsRequest getRootAsLookupStationEventsRequest(ByteBuffer _bb) { return getRootAsLookupStationEventsRequest(_bb, new LookupStationEventsRequest()); }
  public static LookupStationEventsRequest getRootAsLookupStationEventsRequest(ByteBuffer _bb, LookupStationEventsRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public LookupStationEventsRequest __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String stationId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer stationIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public motis.Interval interval() { return interval(new motis.Interval()); }
  public motis.Interval interval(motis.Interval obj) { int o = __offset(6); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public byte type() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static void startLookupStationEventsRequest(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addStationId(FlatBufferBuilder builder, int stationIdOffset) { builder.addOffset(0, stationIdOffset, 0); }
  public static void addInterval(FlatBufferBuilder builder, int intervalOffset) { builder.addStruct(1, intervalOffset, 0); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(2, type, 0); }
  public static int endLookupStationEventsRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

