// automatically generated by the FlatBuffers compiler, do not modify

package motis.lookup;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LookupGeoStationRequest extends Table {
  public static LookupGeoStationRequest getRootAsLookupGeoStationRequest(ByteBuffer _bb) { return getRootAsLookupGeoStationRequest(_bb, new LookupGeoStationRequest()); }
  public static LookupGeoStationRequest getRootAsLookupGeoStationRequest(ByteBuffer _bb, LookupGeoStationRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public LookupGeoStationRequest __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public motis.Position pos() { return pos(new motis.Position()); }
  public motis.Position pos(motis.Position obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public double minRadius() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double maxRadius() { int o = __offset(8); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static void startLookupGeoStationRequest(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addPos(FlatBufferBuilder builder, int posOffset) { builder.addStruct(0, posOffset, 0); }
  public static void addMinRadius(FlatBufferBuilder builder, double minRadius) { builder.addDouble(1, minRadius, 0.0); }
  public static void addMaxRadius(FlatBufferBuilder builder, double maxRadius) { builder.addDouble(2, maxRadius, 0.0); }
  public static int endLookupGeoStationRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

