// automatically generated by the FlatBuffers compiler, do not modify

package motis.lookup;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LookupBatchMetaStationResponse extends Table {
  public static LookupBatchMetaStationResponse getRootAsLookupBatchMetaStationResponse(ByteBuffer _bb) { return getRootAsLookupBatchMetaStationResponse(_bb, new LookupBatchMetaStationResponse()); }
  public static LookupBatchMetaStationResponse getRootAsLookupBatchMetaStationResponse(ByteBuffer _bb, LookupBatchMetaStationResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public LookupBatchMetaStationResponse __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public LookupMetaStationResponse responses(int j) { return responses(new LookupMetaStationResponse(), j); }
  public LookupMetaStationResponse responses(LookupMetaStationResponse obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int responsesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createLookupBatchMetaStationResponse(FlatBufferBuilder builder,
      int responsesOffset) {
    builder.startObject(1);
    LookupBatchMetaStationResponse.addResponses(builder, responsesOffset);
    return LookupBatchMetaStationResponse.endLookupBatchMetaStationResponse(builder);
  }

  public static void startLookupBatchMetaStationResponse(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addResponses(FlatBufferBuilder builder, int responsesOffset) { builder.addOffset(0, responsesOffset, 0); }
  public static int createResponsesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startResponsesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endLookupBatchMetaStationResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

