// automatically generated by the FlatBuffers compiler, do not modify

package motis.lookup;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LookupIdTrainRequest extends Table {
  public static LookupIdTrainRequest getRootAsLookupIdTrainRequest(ByteBuffer _bb) { return getRootAsLookupIdTrainRequest(_bb, new LookupIdTrainRequest()); }
  public static LookupIdTrainRequest getRootAsLookupIdTrainRequest(ByteBuffer _bb, LookupIdTrainRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public LookupIdTrainRequest __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public motis.TripId tripId() { return tripId(new motis.TripId()); }
  public motis.TripId tripId(motis.TripId obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createLookupIdTrainRequest(FlatBufferBuilder builder,
      int trip_idOffset) {
    builder.startObject(1);
    LookupIdTrainRequest.addTripId(builder, trip_idOffset);
    return LookupIdTrainRequest.endLookupIdTrainRequest(builder);
  }

  public static void startLookupIdTrainRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addTripId(FlatBufferBuilder builder, int tripIdOffset) { builder.addOffset(0, tripIdOffset, 0); }
  public static int endLookupIdTrainRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

