// automatically generated by the FlatBuffers compiler, do not modify

package motis.lookup;

public final class TableType {
  private TableType() { }
  public static final byte BOTH = 0;
  public static final byte ONLY_ARRIVALS = 1;
  public static final byte ONLY_DEPARTURES = 2;

  private static final String[] names = { "BOTH", "ONLY_ARRIVALS", "ONLY_DEPARTURES", };

  public static String name(int e) { return names[e]; }
};

